services:
  laskugeneraattori:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - BIND_ADDR=0.0.0.0
      - ALLOWED_ORIGINS=
      - MAILGUN_URL=
      - MAILGUN_USER=
      - MAILGUN_PASSWORD=
      - MAILGUN_TO=
      - MAILGUN_FROM=
    ports:
      - "3000:3000"
    restart: always
